### ISSUE TITLE
Minor bug in plot generation

### ISSUE THREAD

**Issue by stebarb** [lucaros1190/ODE-bactrocera#1]
OdeSolver line 159: ValueError: x and y must have same first dimension, but have shapes (46,) and (1,)
This is due to missing assignment at line 135

**Comment by stebarb** [comment]
I propose the correction
    DevRate[i] = BriFunc_Plot(BriPar_EGG, i)
at line 135 ODE-Solver
Can make pull-request if authorized

**Comment by lucaros1190** [comment]
Hello! Thank you for the comments!
It would be great if you can do a pull-request, thanks! ;)

**Comment by stebarb** [comment]
Thank you for you valuable work! I only need to be granted permission to make my pull-request, that i will gladly do.

**Comment by lucaros1190** [comment]
Thanks! Did you send a pull request? I don't see any request
